# Generated by Django 5.0.6 on 2024-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_porfolio_client_description_porfolio_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfolio',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Portfolio rasmini kiriting'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Portfolio rasmini kiriting'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Portfolio rasmini kiriting'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Portfolio rasmini kiriting'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Portfolio rasmini kiriting'),
        ),
    ]
