# Generated by Django 5.0.6 on 2024-06-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_image',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
