# Generated by Django 5.0.6 on 2024-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_client_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone_num', models.CharField(max_length=13)),
                ('service', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title2',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
