# Generated by Django 5.0.6 on 2024-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_client_about_description_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porfolio',
            old_name='client_description',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='porfolio',
            name='client_description_en',
        ),
        migrations.RemoveField(
            model_name='porfolio',
            name='client_description_ru',
        ),
        migrations.RemoveField(
            model_name='porfolio',
            name='description',
        ),
        migrations.AddField(
            model_name='porfolio',
            name='about_project',
            field=models.TextField(blank=True, null=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='about_project_en',
            field=models.TextField(blank=True, null=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='about_project_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='our_solution',
            field=models.TextField(blank=True, null=True, verbose_name='Our Solution'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='our_solution_en',
            field=models.TextField(blank=True, null=True, verbose_name='Our Solution'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='our_solution_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Our Solution'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='problems',
            field=models.TextField(blank=True, null=True, verbose_name='Problems'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='problems_en',
            field=models.TextField(blank=True, null=True, verbose_name='Problems'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='problems_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Problems'),
        ),
    ]
