# Generated by Django 5.0.6 on 2024-06-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_rename_client_description_porfolio_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
