# Generated by Django 5.0.6 on 2024-06-23 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_porfolio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfolio',
            name='about',
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='about_project_en',
            field=models.TextField(blank=True, null=True, verbose_name='About Project (English)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='about_project_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About Project (Russian)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='client_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Name (English)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='client_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Name (Russian)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Russian)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Russian)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='our_solution_en',
            field=models.TextField(blank=True, null=True, verbose_name='Our Solution (English)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='our_solution_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Our Solution (Russian)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo',
            field=models.ImageField(upload_to='portfolio/photo', verbose_name='Portfolio Photo'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Additional Photo 1'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Additional Photo 2'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Additional Photo 3'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Additional Photo 4'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo', verbose_name='Additional Photo 5'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='problems_en',
            field=models.TextField(blank=True, null=True, verbose_name='Problems (English)'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='problems_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Problems (Russian)'),
        ),
    ]
