# Generated by Django 5.0.6 on 2024-06-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_remove_porfolio_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='category',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
    ]
