# Generated by Django 5.0.6 on 2024-06-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_remove_category_photo_remove_category_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category', verbose_name='Qaysi categoriyaga oidligini kiriting'),
        ),
    ]
