# Generated by Django 5.0.6 on 2024-07-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_subcategory_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolio',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo'),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/photo'),
        ),
    ]
