# Generated by Django 5.0.6 on 2024-07-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_porfolio_photo6_porfolio_photo7'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_light',
            field=models.ImageField(default=1, upload_to='Service/photo', verbose_name='liGhT model uchun ikon'),
            preserve_default=False,
        ),
    ]
