# Generated by Django 5.0.6 on 2024-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_category_icon_light'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
